### ISSUE TITLE
If a risk for meshlet out of order when > 1 subgroups in task shader ?

### ISSUE THREAD

**Issue by toten** [nvpro-samples/gl_vk_meshlet_cadscene#22]
https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/blob/4f6f7f19f34482a5c4c0424116bdfe3f5baa9db8/drawmeshlet_ext.task.glsl#L153

Not sure **if there's a guarantee that multile subgroups will came to this line (atomicAdd) in order** ?

E.g. if there're 2 subgroups are launched (each with 32 threads):
subgroup[0]: process meshlet[0-31]
subgroup[1]: process meshlet[32-63]

If subgroup[1] comes first, and assuming all meshlets survived, then:
OUT.deltaIDs[0-31] will point to meshlet[32-63]. While later (subgroup[0] comes):
OUT.deltaIDs[32-63] will point to meshlet[0-31].

Later when task shader EmitMeshTasksEXT(64, 1, 1), mesh shader workgroups will actually launch to process meshlet in order of:
32, 33, ..., 63, 0, 1, ..., 31, which could results in render failure as no keep for the original primitives order (should be no problem in current sample, but theoretically may be risky).

Is this a risk ?

**Comment by pixeljetstream** [comment]
it is true that rendering order isn't preserved. Though that would only matter if you do something like blending and the exact ordering of meshlets and triangles was an important use-case, which tends to be rare. But you are correct the current implementation wouldn't be order preserving.

**Comment by toten** [comment]
> Though that would only matter if you do something like blending and the exact ordering of meshlets and triangles was an important use-case, which tends to be rare.

Yes, that sounds reasonable.
Thanks a lot.
