### ISSUE TITLE
Viewport not responsive after building

### ISSUE THREAD

**Issue by Tokusei** [nvpro-samples/gl_vk_meshlet_cadscene#3]
Built the vulkan only executable and launched with the respective .cfg files. Viewport is non responsive.

OS: Win10 18362.19h1_release.190318-1202
Windows SDK version 10.0.17763.0
Vulkan SDK 1.1.121.2
 
Had to add 
`#include <stdexcept> 
`
in deviceutils_vk.cpp to build

**Comment by pixeljetstream** [comment]
@Tokusei please try again using the current version of the sample and the framework (shared_sources/shared_external)

**Comment by Tokusei** [comment]
Hi, Sorry for the slow reply.  I have fetched the latest revision of the project and its dependencies. It seems like some of the new files have some encoding issues with my system locale (Chinese) So I will see if I can resolve that then update you with the status

**Comment by Tokusei** [comment]
Hi, I have the vk_meshlet_cadscene built and successfully loading files.

Just two things to note: The SDK needs to be updated to 1.1.126.0 
Seems like some of the files arent working with Chinese system locale (had to switch)
