### ISSUE TITLE
Missing NVMESHLET_VERTEX_ALIGNMENT and NVMESHLET_PRIM_ALIGNMENT defines 

### ISSUE THREAD

**Issue by DaemonDave** [nvpro-samples/gl_vk_meshlet_cadscene#5]
Hello;
I compiled one Linux / Fedora 28 with HAS_OPENGL options not Vulkan and then the glsl shader compiler fails with missing values for NVMESHLET_VERTEX_ALIGNMENT and NVMESHLET_PRIM_ALIGNMENT.

Where would I find these values outside of nvmeshlet_utils.glsl? What should they be?

Thank you,

dave

**Comment by tangogu** [comment]
They are defined in https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/blob/master/config.h line 41/42.
The glsl compiler does not need to compile nvmeshlet_utils.glsl directly since it is included in other GLSL. And those file that include nvmeshlet_utils.glsl will also include the config.h.
