### ISSUE TITLE
model fp16 attributes  no work

### ISSUE THREAD

**Issue by sxin-h** [nvpro-samples/gl_vk_meshlet_cadscene#6]
RT

**Comment by sxin-h** [comment]
nvmeshlet_array.hpp    436-438 line
        vec posA = vec(&positions[idxA * positionMul]);
        vec posB = vec(&positions[idxB * positionMul]);
        vec posC = vec(&positions[idxC * positionMul]);
Error
![image](https://user-images.githubusercontent.com/26243134/103263274-5dcbb580-49e2-11eb-8792-3d2e424efa3e.png)

>

**Comment by pixeljetstream** [comment]
fixed in https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/commit/2404f86d6718bbb747401648b9d2ead2a4fc7b41
