### ISSUE TITLE
PrimitiveCache::fitsBlock() function is always return true

### ISSUE THREAD

**Issue by btrid** [nvpro-samples/gl_vk_meshlet_cadscene#8]
PrimitiveCache::maxBlockBits variable is always constant 0xffffffffu.
These don't seem to make any sense, but are they implementation mistakes?

https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/blob/master/nvmeshlet_builder.hpp#L479
https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/blob/master/nvmeshlet_builder.hpp#L537-L556

**Comment by pixeljetstream** [comment]
this is intentional, as different builder implementations exist. Just one is shipping with the sample, but in research I have different versions and they configure the PrimitiveCache class accordingly
