### ISSUE TITLE
path to download resources doesnot exists 

### ISSUE THREAD

**Issue by nitinp007** [nvpro-samples/gl_vk_meshlet_cadscene#9]
--> using Vulkan Headers from: C:/VulkanSDK/1.3.211.0/Include
Downloading http://developer.download.nvidia.com/ProGraphics/nvpro-samples/worldcar.csf.gz to C:/Users/Local_Admin/Documents/GitHub/cadScene/downloaded_resources/worldcar.csf.gz
Downloading http://developer.download.nvidia.com/ProGraphics/nvpro-samples/blade.csf.gz to C:/Users/Local_Admin/Documents/GitHub/cadScene/downloaded_resources/blade.csf.gz
Configuring done

empty files are downloaded which fails at run time. 

It looks like the path http://developer.download.nvidia.com/ProGraphics/nvpro-samples doesn't exists.

**Comment by vgonakhc** [comment]
Can confirm that blade.csf.gz (Open Cascade format) is nowhere to be found. I found only blade.ply (Stanford Ply).

**Comment by pixeljetstream** [comment]
Both download links work okay. Maybe just unlucky day with connection
